services:
  - type: web
    name: zepto-scraper-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 zepto_scraper:app"
    plan: free
